packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides: 
  ws: 8.21.0
  '@vitejs/plugin-basic-ssl': 2.3.0
  '@mui/icons-material': 7.3.10
  eslint: 10.3.0
  slate: 0.124.1
  'slate-history': 0.113.1
  '@vitejs/plugin-react': 6.0.2
  '@types/node': 25.6.0
  echarts: 6.0.0
  jsdom: 29.1.1
  'brace-expansion': 5.0.6
  turbo: 2.9.14
  esbuild: 0.28.1
  'form-data': 4.0.6
  undici: 7.28.0
  dompurify: 3.4.11
  '@babel/core': "7.29.6"
  jquery: 4.0.0

  
